version: '3.8'

services:
  # Backend API with SQLite - optimized production build
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: customer-health-api
    environment:
      - DATABASE_URL=sqlite:///./data/customer_health.db
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data  # Persistent SQLite storage
      - backend_logs:/app/logs  # Persistent log storage
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend (React) - optimized production build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: customer-health-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  sqlite_data:
    driver: local
  backend_logs:
    driver: local