# Full stack development with both containers
version: '3.8'

services:
  # Backend API with SQLite
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer-health-api-dev
    environment:
      - DATABASE_URL=sqlite:///./data/customer_health.db
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
      - backend_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend in development mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: customer-health-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
  backend_logs:
    driver: local